baseURL = "https://bio.jacktracey.co.uk/"
languageCode = "en"
title = "Jack Tracey - Senior Cloud Solutions Architect"
theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

[params]
  colorPrimary = "#ea9653"
  colorSecondary = "#989898"
  colorPageBackground = "#fff"
  colorRightColumnBackground = "#f0c8a0"
  colorRightColumnHeadingText = "#4a3728"
  colorRightColumnBodyText = "#4a3728"
  colorRightColumnIconPrimary = "#fff"
  colorRightColumnIconBackground = "#ea9653"
  colorIconPrimary = "#fff"
  colorIconBackground = "#ea9653"
  colorLight = "#fff"
  colorDark = "#737374"
  pages = 1
  swapColumns = false
  footerNote = " "
  enableMetaTags = true
